articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('category/<slug>', views.category, name='category'),
    path('', views.article_list, name='list'),
    path('<slug>', views.article_detail, name='detail'),
]

djangonautic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps.views import sitemap
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from django.conf.urls.static import static
from django.conf import settings

from .sitemaps import ArticleSitemap, StaticViewSitemap, CategorySitemap

from .views import home, topmonth
from articles import views as article_views

sitemaps = {
    'articles': ArticleSitemap,
    'static': StaticViewSitemap,
    'flatepages': FlatPageSitemap,
    'categories': CategorySitemap,
}

urlpatterns = [
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}),
    path('robots.txt/', include('robots.urls')),
    path('post/<slug>', article_views.article_detail, name='post'),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('articles/', include('articles.urls')),
    path('topmonth/', topmonth, name='topmonth'),
    path('pages', include('django.contrib.flatpages.urls')),
    path('', home, name='home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
import pytils
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(blank=True)
    description = models.TextField(blank=True, max_length=250)
    keywords = models.TextField(blank=True, max_length=100)
    body = RichTextUploadingField(blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True, db_index=True)
    thumb = models.ImageField(default='default.png', blank=True)
    altfield = models.CharField(max_length=100, default='image-description', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    categories = models.ManyToManyField('Category', blank=True, related_name='articles')

    def __str__(self):
        return self.title

    @property
    def was_published_recently(self):
        return self.date >= (timezone.now() - datetime.timedelta(days = 7))

    def get_absolute_url(self):
        return reverse('post', args=[str(self.slug)])

    def snippet(self): # use it for articles list
        return self.body[:150] + '...'

    def save(self, *args, **kwargs):
        if not self.slug.strip():
            self.slug = pytils.translit.slugify(self.title)
        return super().save(*args, **kwargs)

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    author_name = models.CharField('Prénom', max_length=50)
    author_email = models.EmailField('Email', max_length=50)
    comment_text = models.CharField('Texte', max_length=200)
    date = models.DateTimeField(auto_now_add=True, db_index=True)

    def __str__(self):
        return self.comment_text

    @property
    def human_date(self):
        # Dec 16, 2017 @ 23:05
        return self.date.strftime('%b %e, %Y @ %H:%M')


class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(blank=True)
    describe = models.TextField(blank=False, max_length = 350)

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug.strip():
            self.slug = pytils.translit.slugify(self.title)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('post', args=[str(self.slug)])

    class Meta:
        verbose_name_plural = 'Categories'

articles/forms.py
from django import forms

from .models import Comment

class AddComment(forms.ModelForm):

    def __init__(self, *a, **kw):
        self.article = kw.pop('article', None)
        return super().__init__(*a, **kw)

    def save(self):
        self.instance.article = self.article
        return super().save()
        
    class Meta:
        model = Comment
        fields = ('author_name', 'author_email', 'comment_text')
        widgets = {
            'author_name': forms.TextInput(attrs={'class': 'full-width'}),
            'author_email': forms.TextInput(attrs={'class': 'full-width'}),
            'comment_text': forms.Textarea(attrs={'class': 'full-width'}),
        }

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView, ListView

from .models import Article, Category
from .forms import AddComment

def article_list(request):
    articles = Article.objects.order_by('-date')
    return render(request, 'articles/list.html', {'articles': articles}) 

def article_detail(request, slug):
    article = get_object_or_404(Article, slug=slug)
    try:
        next_article = article.get_next_by_date()
    except Article.DoesNotExist:
        next_article = None
    
    try:
        prev_article = article.get_previous_by_date()
    except Article.DoesNotExist:
        prev_article = None
    
    comments = article.comments.filter()
    if request.method == 'POST':
        data = request.POST.dict()
        form = AddComment(data=data, article=article)
        if form.is_valid():
            form.save()
    else:
        form = AddComment()
    return render(request, 'articles/detail.html', {
        'article': article,
        'next_article': next_article,
        'prev_article': prev_article,
        'comments': comments, 
        'form': form,
    })

def category(request, slug):
    category = Category.objects.get(slug=slug)
    articles = category.articles.order_by('-date')
    return render(request, 'articles/list.html', {'category': category, 'articles': articles})

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

from articles.models import Article

def home(request):
    articles = Article.objects.order_by('-date')
    return render(request, 'home.html', {'articles': articles, 'hide_description': True})

def topmonth(request):
    return render(request, 'topmonth.html')

articles/templates/articles/detail.html
{% extends 'home.html' %}
{% load l10n %}

{% block title %}{{ article.title }}{% endblock %}

{% block description %}{{ article.description }}{% endblock %}

{% block keywords %}, {{ article.keywords }}{% endblock %}

{% block content %}
<section class="s-content s-content--narrow s-content--no-padding-bottom">
    <article class="row format-standard">

        <div class="s-content__header col-full">
            <h1 class="s-content__header-title">
                {{ article.title }}
            </h1>
            <ul class="s-content__header-meta">
                <li class="date">
                    {% localize on %}
                    {{ article.date|date:"E j, Y" }}
                    {% endlocalize %}
                </li>
                <li class="cat">
                    {% for category in article.categories.all %}
                    <a href="{% url 'articles:category' slug=category.slug %}">{{ category.title }}</a>
                    {% endfor %}
                </li> <br>
                <li class="date">
                    L'auteur: <a href="https://www.instagram.com/vladkomudrich/">{{ article.author }}</a>
                </li>
            </ul>
        </div>
        
        <div class="s-content__media col-full">
            <div class="s-content__post-thumb">
                <img src="{{ article.thumb.url }}" alt="{{ article.altfield }}" title="{{ article.title }}">
            </div>
        </div>

        <div class="col-full s-content__main">
            {{ article.body|safe }}

            <div class="s-content__pagenav">
                <div class="s-content__nav">
                    <div class="s-content__prev">
                        {% if prev_article %}
                        <a href="{% url 'articles:detail' prev_article.slug %}" rel="prev">
                            <strong>Previous article</strong><br>
                            <span>{{ prev_article.title }}</span>
                        </a>
                        {% endif %}
                    </div>
                    <div class="s-content__next">
                        {% if next_article %}
                        <a href="{% url 'articles:detail' next_article.slug %}" rel="next">
                            <strong>Next article</strong>
                            <span>{{ next_article.title }}</span>
                        </a>
                        {% endif %}
                    </div>
                </div>
            </div>

        </div>

    </article>

    <div class="comments-wrap">

        <div id="comments" class="row">
            <div class="col-full">
                {% if comments %}
                <a name="comments"></a>
                <h3 class="h2">{{ comments|length }} Comments</h3>

                <ol class="commentlist">
                    {% for comment in comments %}
                    <li class="depth-1 comment">
                        <div class="comment__avatar">
                        </div>
                        <div class="comment__content">
                            <div class="comment__info">
                                <cite>{{ comment.author_name }}</cite>

                                <div class="comment__meta">
                                    <time class="comment__time">{{ comment.human_date }}</time>
                                </div>
                            </div>
                            <div class="comment__text">
                                <p>{{ comment.comment_text }}</p>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ol>
                {% endif %}

                <div class="respond">
                    <a name="form"></a>
                    <h3 class="h2">Ajoutez un commentaire</h3>
                    <form name="contactForm" id="contactForm" method="post" action="#" novalidate>
                        {% csrf_token %}
                        <fieldset>
                            {{ form.as_p }}
                            <button type="submit" class="submit btn--primary btn--large full-width">Envoyer</button>
                        </fieldset>
                    </form>

                </div>
            </div>
        </div>
    </div>
</section>
<script>
    (function () {
    {% if form.is_valid %}
    setTimeout(function () {
        window.location.hash = 'comments'
    })
    {% endif %}
    })()
</script>
{% endblock %}

articles/templates/articles/list.html
{% extends "home.html" %}
{% load l10n %}

{% block top %}
{% endblock %}

templates/base.html
{% load static %}
{% load l10n %}

<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}Title{% endblock %}</title>
    <meta name="description" content="{% block description %}Info for description tag (for SEO){% endblock %}">
    <meta name="author" content="vladkomudrich">
    <meta name="keywords" content="some keywords{% block keywords %}{% endblock %}">

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/vendor.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <script src="{% static 'js/modernizr.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>

    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">

</head>

<body id="top">

    <div class="s-pageheader">

        <header class="header">
            <div class="header__content row">

                <div class="header__logo">
                    <a class="logo" href="{% url 'home' %}">
                        <!-- <img src="{% static 'path/to/image' %}" alt="Homepage"> -->
                        Blog Title (try to add .jpg/.png logo here)
                    </a>
                </div>

                <ul class="header__social">
                    <li>
                        <a href="https://vk.com/vladkomudrich"><i class="fa fa-vk" aria-hidden="true"></i></a>
                    </li>
                    <li>
                        <a href="https://www.instagram.com/vladkomudrich"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                    </li>
                </ul>
                {% comment %}
                <a class="header__search-trigger" href="#0"></a>

                <div class="header__search">

                    <form role="search" method="get" class="header__search-form" action="#">
                        <label>
                            <span class="hide-content">Search for:</span>
                            <input type="search" class="search-field" placeholder="Type Keywords" value="" name="s" title="Search for:" autocomplete="off">
                        </label>
                        <input type="submit" class="search-submit" value="Search">
                    </form>
        
                    <a href="#0" title="Close Search" class="header__overlay-close">Close</a>

                </div>
                {% endcomment %}

                <a class="header__toggle-menu" href="#0" title="Menu"><span>Menu</span></a>

                <nav class="header__nav-wrap">

                    <h2 class="header__nav-heading h6">Site Navigation</h2>

                    <ul class="header__nav">
                        <li><a href="{% url 'home' %}" title="">Home</a></li>
                        <li class="has-children">
                            <a href="#0" title="">Categories</a>
                            <ul class="sub-menu">
                                {% for category in categories %}
                                <li>
                                    <a href="{% url 'articles:category' slug=category.slug %}">{{ category.title }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                        <li><a href="{% url 'articles:list' %}" title="">Blog</a></li>
                        <li><a href="{% url 'topmonth' %}" title="">Best</a></li>
                        <li class="current"><a href="{% url 'django.contrib.flatpages.views.flatpage' url='/about/' %}" title="">About</a></li>
                    </ul>

                    <a href="#0" title="Close Menu" class="header__overlay-close close-mobile-menu">Close</a>

                </nav>

            </div>
        </header>
        {% block top %}{% endblock %}
    </div>
    
    {% block content %}
    {% endblock %}
    
    <footer class="s-footer">

        <div class="s-footer__main">
            <div class="row">
                
                <div class="col-two md-four mob-full s-footer__sitelinks">
                        
                    <h4>Quick links</h4>

                    <ul class="s-footer__linklist">
                        <li><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="{% url 'articles:list' %}">Blog</a></li>
                        {% for category in categories %}
                                <li>
                                    <a href="{% url 'articles:category' slug=category.slug %}">{{ category.title }}</a>
                                </li>
                                {% endfor %}
                        <li><a href="{% url 'topmonth' %}">Best</a></li>
                        <li><a href="/about/">About</a></li>
                    </ul>

                </div>

                <div class="col-two md-four mob-full s-footer__social">
                        
                    <h4>Social networks</h4>

                    <ul class="s-footer__linklist">
                        <li><a href="https://vk.com/vladkomudrich">VK</a></li>
                        <li><a href="https://www.instagram.com/vladkomudrich">Instagram</a></li>
                    </ul>

                </div>

            

            </div>
        </div>

        <div class="s-footer__bottom">
            <div class="row">
                <div class="col-full">
                        <span>Made by <a href="https://www.instagram.com/vladkomudrich">vladkomudrich</a> 2019-2020</span> 
                    </div>

                    <div class="go-top">
                        <a class="smoothscroll" title="Back to Top" href="#top"></a>
                    </div>
                </div>
            </div>
        </div>

    </footer>

    <div id="preloader">
        <div id="loader">
            <div class="line-scale">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </div>
        </div>
    </div>

    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load l10n %}

{% block top %}
{% comment %}

<div class="pageheader-content row">
    <div class="col-full">

        <div class="featured">

            <div class="featured__column featured__column--big">
                <div class="entry" style="background-image:url('images/thumbs/featured/featured-guitarman.jpg');">
                    
                    <div class="entry__content">
                        <span class="entry__category"><a href="#0">Music</a></span>

                        <h1><a href="#0" title="">What Your Music Preference Says About You and Your Personality.</a></h1>

                        <div class="entry__info">
                            <a href="#0" class="entry__profile-pic">
                                <img class="avatar" src="images/avatars/user-03.jpg" alt="">
                            </a>

                            <ul class="entry__meta">
                                <li><a href="#0">John Doe</a></li>
                                <li>December 29, 2017</li>
                            </ul>
                        </div>
                    </div>
                    
                </div>
            </div>

            <div class="featured__column featured__column--small">

                <div class="entry" style="background-image:url('images/thumbs/featured/featured-watch.jpg');">
                    
                    <div class="entry__content">
                        <span class="entry__category"><a href="#0">Management</a></span>

                        <h1><a href="#0" title="">The Pomodoro Technique Really Works.</a></h1>

                        <div class="entry__info">
                            <a href="#0" class="entry__profile-pic">
                                <img class="avatar" src="images/avatars/user-03.jpg" alt="">
                            </a>

                            <ul class="entry__meta">
                                <li><a href="#0">John Doe</a></li>
                                <li>December 27, 2017</li>
                            </ul>
                        </div>
                    </div>
                    
                </div>

                <div class="entry" style="background-image:url('images/thumbs/featured/featured-beetle.jpg');">

                    <div class="entry__content">
                        <span class="entry__category"><a href="#0">LifeStyle</a></span>

                        <h1><a href="#0" title="">Throwback To The Good Old Days.</a></h1>

                        <div class="entry__info">
                            <a href="#0" class="entry__profile-pic">
                                <img class="avatar" src="images/avatars/user-03.jpg" alt="">
                            </a>

                            <ul class="entry__meta">
                                <li><a href="#0">John Doe</a></li>
                                <li>December 21, 2017</li>
                            </ul>
                        </div>
                    </div>

                </div>

            </div>
        </div>

    </div>
</div>
{% endcomment %}
{% endblock %}

{% block content %}
<section class="s-content">
    {% if not hide_description %}
    <div class="row narrow">
        <div class="col-full s-content__header" data-aos="fade-up">
            <h1>{{ category.title |default:'Blog' }}</h1>
            <p class="lead">{{ category.describe|default:"Ici, nous avons rassemblé tous nos articles" }}</p>
        </div>
    </div>
    {% endif %}
    
    <div class="row masonry-wrap">
        <div class="masonry">

            <div class="grid-sizer"></div>

            {% for article in articles %}
            <article class="masonry__brick entry format-standard" data-aos="fade-up">
                
                <div class="entry__thumb">
                    <a href="{% url 'articles:detail' slug=article.slug %}" class="entry__thumb-link">
                        <img src="{{ article.thumb.url }}" alt="{{ article.altfield }}" title="{{ article.title }}">
                    </a>
                </div>
                
                <div class="entry__text">
                    <div class="entry__header">
                        
                        <div class="entry__date">
                            <a href="{% url 'articles:detail' slug=article.slug %}">
                                {% localize on %}
                                {{ article.date|date:"E j, Y" }}
                                {% endlocalize %}
                            </a>
                        </div>
                        <h1 class="entry__title"><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h1>
                        
                    </div>
                    <div class="entry__excerpt">
                        <p>
                            {{ article.snippet|safe }}
                        </p>
                    </div>
                    <div class="entry__meta">
                        <span class="entry__meta-links">
                            {% for category in article.categories.all %}
                            <a href="{% url 'articles:category' slug=category.slug %}">{{ category.title }}</a>
                            {% endfor %}
                        </span>
                    </div>
                </div>
                
            </article>
            {% endfor %}


        </div>
    </div>

    {% comment %}
    <div class="row">
        <div class="col-full">
            <nav class="pgn">
                <ul>
                    <li><a class="pgn__prev" href="#0">Prev</a></li>
                    <li><a class="pgn__num" href="#0">1</a></li>
                    <li><span class="pgn__num current">2</span></li>
                    <li><a class="pgn__num" href="#0">3</a></li>
                    <li><a class="pgn__num" href="#0">4</a></li>
                    <li><a class="pgn__num" href="#0">5</a></li>
                    <li><span class="pgn__num dots">...</span></li>
                    <li><a class="pgn__num" href="#0">8</a></li>
                    <li><a class="pgn__next" href="#0">Next</a></li>
                </ul>
            </nav>
        </div>
    </div>
    {% endcomment %}

</section>

<section class="s-extra">

    <div class="row bottom tags-wrap">
        <div class="col-full tags">
            <h3>Catégories</h3>
            <div class="tagcloud">
                {% for category in categories %}
                <a href="{% url 'articles:category' slug=category.slug %}">{{ category.title }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock%}

templates/topmonth.html
{% extends 'base.html' %}

{% block content %}
<section class="s-content">
    <div class="row narrow">
        <div class="col-full s-content__header" data-aos="fade-up">
            <h1>Continue to develop this Blog!</h1>
        </div>
    </div>
</section>
{% endblock %}